/* exported Events */
var Events = {
	PLAY: "PLAY",
	PAUSE: "PAUSE",
	FULLSCREEN: "FULLSCREEN",
	CC: "CC",
	GO_LIVE: "GO_LIVE",
	IS_LIVE: "IS_LIVE",
	MUTE: "MUTE",
	VOLUME: "VOLUME",
	UNMUTE: "UNMUTE",
	REWIND: "REWIND",
	SEEK: "SEEK"
};

