/* exported Events */
var Events = {
	PLAY: "PLAY",
	PAUSE: "PAUSE",
	FULLSCREEN: "FULLSCREEN",
	CC: "CC",
	GO_LIVE: "GO_LIVE",
	IS_LIVE: "IS_LIVE",
	MUTE: "MUTE",
	SHOW_SHARE: "show:share",
	SHARE_EMBED: "SHARE_EMBED",
	SHARE_LINK: "SHARE_LINK",
	SHARE: "share",
	VOLUME: "VOLUME",
	UNMUTE: "UNMUTE",
	REWIND: "REWIND",
	SEEK: "SEEK",
	SCRUB_START: "SCRUB_START",
	SCRUBBING: "SCRUBBING",
	LEARN_MORE: "LEARN_MORE"
};
